<a href="https://colab.research.google.com/github/kabutie-dej/dsc-data-analysis-python-intro/blob/master/index.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Getting Started with NumPy - Lab

## Introduction

Now that we have introduced NumPy, let's put it to practice. In this lab, you are going to be creating arrays, performing operations on them, and returning new arrays all using the NumPy library. Let's get started!

## Objectives

You will be able to:

- Instantiate a numpy array with specified values
- Use broadcasting to perform a math operation on an entire numpy array


## Import `NumPy` under the standard alias

In [1]:
# Import numpy using the standard alias
import numpy as np

## Generate some mock data

Create a NumPy array for each of the following:
    1. Using a range
    2. Using a Python list
    
Below, create a list in Python that has 5 elements (i.e. [0,1,2,3,4]) and assign it to the variable `py_list`.

Next, do the same, but instead of a list, create a range with 5 elements and assign it to the variable, `py_range`.

Finally, use the list and range to create NumPy arrays and assign the array from list to the variable `array_from_list`, and the array from the range to the variable `array_from_range`.

In [3]:
# Your code here
py_list = [0,1,2,3,4]
py_range = (range(5))
array_from_list = np.array(py_list)
array_from_range = np.array(py_range)
array_from_list
array_from_range

array([0, 1, 2, 3, 4])

Next, we have a list of heights and weights and we'd like to use them to create a collection of BMIs. However, they are both in inches and pounds (imperial system), respectively.

Let's use what we know to create NumPy arrays with the metric equivalent values (height in meters & weight in kg).

> **Remember:** *NumPy can make these calculations a lot easier and with less code than a list!*

> 1.0 inch = 0.0254 meters

> 2.2046 lbs = 1 kilogram

In [4]:
# Use the conversion rate for turning height in inches to meters
list_height_inches = [65, 68, 73, 75, 78]

array_height_inches =  np.array(list_height_inches)
array_height_meters =  np.array(list_height_inches)* 0.0254
array_height_meters

array([1.651 , 1.7272, 1.8542, 1.905 , 1.9812])

In [8]:
# Use the conversion rate for turning weight in pounds to kilograms
list_weight_pounds = [150, 140, 220, 205, 265]

# Your code here
array_weight_pounds = np.array(list_weight_pounds)
array_weight_kg = array_weight_pounds / 2.2046
array_weight_kg

array([ 68.03955366,  63.50358342,  99.79134537,  92.98739   ,
       120.20321147])

The metric formula for calculating BMI is as follows:

> BMI = weight (kg) ÷ height^2 (m^2)

So, to get BMI we divide weight by the squared value of height. For example, if I weighed 130kg and was 1.9 meters tall, the calculation would look like:

> BMI = 130 / (1.9*1.9)

Use the BMI calculation to create a NumPy array of BMIs

In [22]:
# Your code
BMI_array = np.array(130/(1.9*1.9))
BMI_array

array(36.01108033)

## Create a vector of ones the same size as your BMI vector using `np.ones()`

In [23]:
# Your code here
identity = np.ones(5)
identity

array([1., 1., 1., 1., 1.])

## Multiply the BMI_array by your vector of ones
The resulting product should have the same values as your original BMI numpy array.

In [24]:
# Your code here
BMI_array * identity

array([36.01108033, 36.01108033, 36.01108033, 36.01108033, 36.01108033])

In [25]:
np.multiply(BMI_array,identity)

array([36.01108033, 36.01108033, 36.01108033, 36.01108033, 36.01108033])

## Level Up: Using NumPy to Parse a File
The Pandas library that we've been using is built on top of NumPy; all columns/series in a Pandas DataFrame are built using NumPy arrays. To get a better idea of a how a built-in method like `pd.read_csv()` works, we'll try and recreate that here!

In [31]:
# Open a text file (csv files are just plaintext separated by commas)
import numpy as np
import pandas as pd
pd.read_csv('bp.text')
f = open('bp.txt')
n_rows = len(f.readlines())
# Print number of lines in the file
print('The file has {} lines.'.format(n_rows))
# After using readlines, we must reopen the file
f = open('bp.txt')
# The file has values separated by tabs; we read the first line and check it's length
n_cols = (len(f.readline().split('\t')))

f = open('bp.txt')
data = np.zeros(n_rows , n_cols -1)
for line in f: enumerate (data)
n_rows = data
data


# Your code here
# Pseudocode outline below
#1) Create a matrix of zeros that is the same size of the file
#2) Iterate through the file: "for line in f:" Hint: using enumerate will also be required
    #3) Update each row of the matrix with the new stream of data
    #Hint: skip the first row (it's just column names, not the data.)
#4) Preview your results; you should now have a NumPy matrix with the data from the file


FileNotFoundError: [Errno 2] No such file or directory: 'bp.text'

## Summary

In this lab, we practiced creating NumPy arrays from both lists and ranges. We then practiced performing math operations like converting imperial measurements to metric measurements on each element of a NumPy array to create new arrays with new values. Finally, we used both of our new NumPy arrays to operate on each other and create new arrays containing the BMIs from our arrays containing heights and weights.